## Remote package repositories
arch aarch64_generic 10
arch aarch64_cortex-a53 15

src/gz immortalwrt_core https://downloads.immortalwrt.org/releases/24.10.2/targets/rockchip/armv8/packages
src/gz immortalwrt_base https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_generic/base
src/gz immortalwrt_kmods https://downloads.immortalwrt.org/releases/24.10.2/targets/rockchip/armv8/kmods/6.6.93-1-9e686cc1e0d5129337ca1ca28c2ab984
src/gz immortalwrt_luci https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_generic/luci
src/gz immortalwrt_packages https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_generic/packages
src/gz immortalwrt_routing https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_generic/routing
src/gz immortalwrt_telephony https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_generic/telephony

## This is the local package repository, do not remove!
src imagebuilder file:packages

option check_signature
